---
# tasks for configure

- name: "Be sure to have created needed directory on the existent volume"
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
   - "{{ common['volumes'][0]['volume_path'] }}/var"
   - "{{ common['volumes'][0]['volume_path'] }}/var/log"
  when:
   - common is defined
   - common['volumes'][0]['volume_path'] is defined
   - common['volumes'][0]['volume_path'] != ""

- name: "Be sure to configure correctly the Rsyslog server"
  template:
   src: conf/relp.conf.j2
   dest: "/etc/rsyslog.d/22-relp.conf"
   owner: "root"
   group: "root"
   mode: 0644
  notify:
   - "Restart Rsyslog"
