---
# file: site.yml
- import_playbook: elasticsearch-servers.yml
- import_playbook: kibana-servers.yml
- import_playbook: checkmk-servers.yml
- import_playbook: rsyslog-servers.yml
- import_playbook: rsnapshot-servers.yml
