---
# tasks for configure an external backup server

- name: "Be sure that the backup private ssh key is in /root/.ssh/"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/{{ rsnapshot['ext-backup']['ssh_priv_key'] }}"
   dest: "/root/.ssh/{{ rsnapshot['ext-backup']['ssh_priv_key'] }}"
   owner: root
   group: root
   mode: 0600
    
- name: "Be sure that the backup public ssh key is in /root/.ssh/"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/{{ rsnapshot['ext-backup']['ssh_pub_key'] }}"
   dest: "/root/.ssh/{{ rsnapshot['ext-backup']['ssh_pub_key'] }}"
   owner: root
   group: root
   mode: 0644

- name: "Be sure to have a cron job for the external backup"
  template:
   src: ext-backup.j2
   dest: "/etc/cron.d/ext-backup"
   owner: root
   group: root
   mode: 0644
