---
# task for elasticsearch

#- name: "Include OS-specific variables."
#  include_vars: "{{ ansible_os_family }}.yml"
#  tags: elasticsearch

- name: "Install Elasticsearch"
  import_tasks: "install.yml"
  tags: elasticsearch

- name: "Configure Elasticsearch"
  import_tasks: "configure.yml"
  tags: elasticsearch
