---
# tasks for configure

- name: "Be sure to have created needed directory on the existent volume"
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
   - "{{ common['volumes'][0]['volume_path'] }}/var"
   - "{{ common['volumes'][0]['volume_path'] }}/var/log"
  when:
   - common is defined
   - common['volumes'][0]['volume_path'] is defined
   - common['volumes'][0]['volume_path'] != ""

- name: "Be sure to add the authorized key"
  authorized_key:
   user: root
   state: present
   key: "{{ rsync['config']['ssh_pub_key'] }}"
  when:
   - rsync is defined
   - rsync['config'] is defined
   - rsync['config'] is defined
   - rsync['config']['ssh_pub_key'] is defined
   - rsync['config']['ssh_pub_key'] != ""

