---
# tasks file for checkmk

#- name: "Include OS-specific variables."
#  include_vars: "{{ ansible_os_family }}.yml"
#  tags: checkmk

- name: "Install Check MK"
  import_tasks: "install.yml"
  tags: checkmk

- name: "Configure Check MK"
  import_tasks: "configure.yml"
  tags: checkmk

- name: "Update Check MK"
  import_tasks: "update.yml"
  tags: checkmk_upd

